### PR TITLE
Global styling

### LINKED ISSUE #244: Global styling
Add global styling for simple components.

### PR DESCRIPTION
**Pull request by emneirin**
In this PR I cleanup the styling globally, make it more consistent, responsive and intuitive.

You're free to review the code itself, but these are mostly styling edits and no functional code edits.

closes #244

### CODE REVIEW

**Review by GashinRS — APPROVED** [review]

**Comment by TiboStr** [comment]
When clicking on "bewerk" as syndic. `PatchBuildingSyndicModal` should pop up.

image

**Comment by TiboStr** [comment]
Since the application is in Dutch, maybe you could translate "go to login"?

image

**Review by n00bS-oWn-m3 — APPROVED** [review]
Looks extremely professional!

**Comment by TiboStr** [comment]
Maybe a space between "contacteer" and the email address?

image

**Comment by TiboStr** [comment]
* "Publiek`e`" instead of "Publiek"?
* And maybe add a tooltip for "Klant ID" to explain what this is (like we did for public id)

image

**Comment by TiboStr** [comment]
Maybe you could steal the dr trottoir favicon (https://drtrottoir.be/favicon.ico) and use it in our application.

**Review by simvadnbu — APPROVED** [review]

**Pull request merged**
