### PR TITLE
Add missing translations (fix #554)

### LINKED ISSUE #554: Missing translations
image

### PR DESCRIPTION
**Pull request by TiboStr**
Closes #554

### CODE REVIEW

**Comment by TiboStr** [comment]
@n00bS-oWn-m3, the GH fails.

**Review by jonathancasters — APPROVED** [review]

**Comment by jonathancasters** [comment]
Still one missing, I suppose?

image

**Comment by TiboStr** [comment]
> Still one missing, I suppose?
> 
> image

The reason it was translated locally on my machine, was because there were translations of `venv` in the `.po` file. I think I fixed it with an extra middleware.

**Review by n00bS-oWn-m3 — APPROVED** [review]
looks like you already fixed the issue in the `docker-compose.yml` file. good job!

**Pull request merged**
