### PR TITLE
Add space in syndic footer

### PR DESCRIPTION
**Pull request by TiboStr**
Very important last minute fix

### CODE REVIEW

**Review by simvadnbu — APPROVED** [review]
Wel spotted 👀 ! This will make sure the app won't break. 👌

**Review by emneirin — APPROVED** [review]

**Review by n00bS-oWn-m3 — APPROVED** [review]
Keen eye

**Comment by TiboStr** [comment]
Guys, I actually screwed this 1 line PR up. There are 2 spaces instead of one. 

Alt Text

I'll work on a fix!

**Review by jonathancasters — APPROVED** [review]

**Review by jonathancasters — APPROVED** [review]

**Review by sevrijss — APPROVED** [review]

**Review by simvadnbu — APPROVED** [review]
Good thinking for re-requesting a review as the new commits change a lot. 👌

**Pull request merged**
